-- ▣ 테이블 삭제
-- DROP TABLE TBL_CURRICULUM;

-- ▣ 테이블 생성
CREATE TABLE TBL_CURRICULUM
(  
  CURRIC_CODE NUMBER(8) NOT NULL
, CURRIC_NAME VARCHAR2(64)  NOT NULL
, CONSTRAINT TBL_CURRICULUM_PK PRIMARY KEY(CURRIC_CODE)
);
-- ==>> Table TBL_CURRICULUM이(가) 생성되었습니다.

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_CURRICULUM IS '과정리스트 정적_테이블';
COMMENT ON COLUMN TBL_CURRICULUM.CURRIC_CODE IS '과정코드';
COMMENT ON COLUMN TBL_CURRICULUM.CURRIC_NAME IS '과정명';
-- ==>> Comment이(가) 생성되었습니다.


-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_CURRICULUM
       INCREMENT BY 1
       START WITH 80000001
       MINVALUE 80000001
       MAXVALUE 84000000
       NOCYCLE
       NOCACHE
       NOORDER;
-- ==>> Sequence SEQ_CURRICULUM이(가) 생성되었습니다.


-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_CURRICULUM



-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.