-- ▣ 테이블 삭제
-- DROP TABLE TBL_CURRICULUM;

-- ▣ 테이블 생성
CREATE TABLE TBL_CURRICULUM
(  
  CURRIC_CODE NUMBER(6) NOT NULL
, CURRIC_NAME VARCHAR2(64)  NOT NULL
, CONSTRAINT TBL_CURRICULUM_PK PRIMARY KEY(CURRIC_CODE)
);
-- ==>> Table TBL_CURRICULUM이(가) 생성되었습니다.

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_CURRICULUM IS '과정리스트 정적_테이블';
COMMENT ON COLUMN TBL_CURRICULUM.CURRIC_CODE IS '과정코드';
COMMENT ON COLUMN TBL_CURRICULUM.CURRIC_NAME IS '과정명';
-- ==>> Comment이(가) 생성되었습니다.
