-- ▣ 테이블 삭제
-- DROP TABLE TBL_SUBJECT;

-- ▣ 테이블 생성
CREATE TABLE TBL_SUBJECT
(
  SUBJ_CODE NUMBER(8)  NOT NULL,
  SUBJ_NAME VARCHAR2(64) NOT NULL,
  CONSTRAINT PK_TBL_SUBJECT PRIMARY KEY(SUBJ_CODE)
);
-- ==>> Table TBL_SUBJECT이(가) 생성되었습니다.

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_SUBJECT IS '과목리스트_정적_테이블';
COMMENT ON COLUMN TBL_SUBJECT.SUBJ_CODE IS '과목코드';
COMMENT ON COLUMN TBL_SUBJECT.SUBJ_NAME IS '과목명';
-- ==>> Comment이(가) 생성되었습니다.

-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_SUBJ
       INCREMENT BY 1
       START WITH 80000001
       MINVALUE 80000001
       MAXVALUE 80100000
       NOCYCLE
       NOCACHE
       NOORDER;
-- ==>> Sequence SEQ_SUBJ이(가) 생성되었습니다.


-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_SUBJ



-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.