-- ▣ 테이블 삭제
-- DROP TABLE TBL_SUBJECT;

-- ▣ 테이블 생성
CREATE TABLE TBL_SUBJECT
(
  SUBJ_CODE NUMBER(6)  NOT NULL,
  SUBJ_NAME VARCHAR2(64) NOT NULL,
  CONSTRAINT PK_TBL_SUBJECT PRIMARY KEY(SUBJ_CODE)
);
-- ==>> Table TBL_SUBJECT이(가) 생성되었습니다.

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_SUBJECT IS '과목리스트_정적_테이블';
COMMENT ON COLUMN TBL_SUBJECT.SUBJ_CODE IS '과목코드';
COMMENT ON COLUMN TBL_SUBJECT.SUBJ_NAME IS '과목명';
-- ==>> Comment이(가) 생성되었습니다.

