-- ▣ 테이블 삭제
-- DROP TABLE TBL_TEXTBOOK;

-- ▣ 테이블 생성
CREATE TABLE TBL_TEXTBOOK
(
  TB_CODE     NUMBER(8)  NOT NULL
, TB_NAME     VARCHAR2(32) NOT NULL
, TB_WRITER   VARCHAR2(128)
, TB_PUB_YEAR VARCHAR2(8)
, CONSTRAINT TBL_TEXTBOOK_PK PRIMARY KEY(TB_CODE)
);
-- ==> TBL_TEXTBOOK이(가) 생성되었습니다.

-- ▣ 컬럼 속성 변경
-- ALTER TABLE TBL_TEXTBOOK MODIFY TB_NAME VARCHAR2(128);
ALTER TABLE TBL_TEXTBOOK MODIFY TB_WRITER VARCHAR2(128);

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_TEXTBOOK IS '교재리스트_정적_테이블';
COMMENT ON COLUMN TBL_TEXTBOOK.TB_CODE IS '교재코드';
COMMENT ON COLUMN TBL_TEXTBOOK.TB_NAME IS '교재명';
COMMENT ON COLUMN TBL_TEXTBOOK.TB_WRITER IS '저자';
COMMENT ON COLUMN TBL_TEXTBOOK.TB_PUB_YEAR IS '발생년도';
-- ==>> Comment이(가) 생성되었습니다.

-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_TEXTBOOK
       INCREMENT BY 1
       START WITH 74000001
       MINVALUE 74000001
       MAXVALUE 80000000
       NOCYCLE
       NOCACHE
       NOORDER;
-- ==>> Sequence SEQ_TEXTBOOK이(가) 생성되었습니다.


-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_TEXTBOOK

-- ▣ 데이터 삭제
-- DELETE FROM TBL_TEXTBOOK;

-- ▣ 데이터 입력
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 플러터 앱 개발 & 출시하기 - 개정판', '조준수', '2025');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 5일 만에 끝내는 깃 & 깃허브 입문', '고경희, 이고잉', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 깡샘의 플러터 & 다트 프로그래밍', '강성윤', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 챗GPT & 파이썬으로 AI 직원 만들기', '이성용', '2023');

INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, ' ', ' ', ' ');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 알고리즘 코딩 테스트 자바 편 — 개정판', '김종관', '2025');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 클린 프로그래밍', '김종관', '2025');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! JSCODE의 AWS 입문', '박재성', '2025');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! LLM을 활용한 AI 에이전트 개발 입문', '이성용', '2025');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 오토캐드 2026', '박한울', '2025');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 스위프트로 아이폰 앱 만들기 입문 ━ 개정 8판', '송호정, 이범근', '2025');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 오라클로 배우는 SQL 입문', '이지훈', '2025');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 깡샘의 안드로이드 앱 프로그래밍 with 코틀린 - 개정 4판', '강성윤', '2025');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 자바 프로그래밍 입문 - 개정판', '박은종', '2025');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 자바스크립트+제이쿼리 입문 - 개정 2판', '정인용', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 코드 없이 배우는 데이터 분석 with 오렌지3', '권서림', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! IT 서비스 이해를 위한 네트워크 기초', '심준보', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 스케치업 with 엔스케이프 - 전면 개정판', '최주영', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 오토캐드 2025', '박한울', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 조코딩의 첫 웹 개발', '조동근, 조경민', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! MySQL로 배우는 SQL 입문', '강성욱', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! C++ 완전 정복', '조규남, 문종채', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! HTML+CSS+자바스크립트 웹 표준의 정석 ━ 전면 개정판', '고경희', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 리액트로 웹앱 만들기 with 타입스크립트', '전예홍', '202');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 웹 디자인 교과서', '정경희', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 일상이 자동화되는 파이썬 생활 프로그래밍 with 챗GPT', '김창현', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 시뮬레이터+키트로 완성하는 아두이노 입문', '박필준', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 웹 사이트 기획 입문 - 전면 개정판', '이정원', '2024');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 점프 투 스프링 부트 3', '박응용', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 실무 순서로 배우는 프로덕트 디자인 with 피그마', '이상효', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 데이터 분석을 위한 판다스 입문 ─ 전면 개정판', '다니엘 첸', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! Node.js 프로그래밍 입문', '고경희', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 구글 애널리틱스 4', '한수창, 이준성', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 데이터 과학자를 위한 실전 머신러닝', '배기웅', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 프런트엔드 UI 개발 with Vue.js', '김윤미', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 점프 투 자바', '박응용', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 점프 투 파이썬 - 전면 개정 2판', '박응용', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 오토캐드 2024', '박한울', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 첫 알고리즘', '마츠우라 켄이치로, 츠카사 유키', '2023');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 알고리즘 코딩 테스트 - C++ 편', '김종관', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 게임 10개 만들며 배우는 파이썬', '벤 포터, 쉬무엘 포터', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 깡샘의 안드로이드 앱 프로그래밍 with 코틀린 — 개정 2판', '강성윤', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 모던 자바스크립트 프로그래밍의 정석', '고경희', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! C# 프로그래밍 입문', '박필준', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 자료구조와 함께 배우는 알고리즘 입문 - C 언어 편 [전면 개정판]', '시바타 보요', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'IT 5분 잡학사전', '니꼴라스, 배지현', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 알고리즘 코딩 테스트 - 파이썬 편', '김종관', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 조코딩의 프로그래밍 입문', '조동근, 김형태', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! SQL 입문', '강성욱', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, '인공지능은 게임을 어떻게 움직이는가?', '미야케 요이치로', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 쉽게 배우는 파이썬 데이터 분석', '김영우', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 공공데이터로 배우는 R 데이터 분석 with 샤이니', '김철민', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 점프 투 파이썬 - 라이브러리 예제 편', '박응용', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 클론 코딩 줌', '니꼴라스, 강윤호', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 자료구조와 함께 배우는 알고리즘 입문 ― 자바 편(전면 개정판)', '시바타 보요', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 첫 인공지능', '이애리', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 알고리즘 코딩 테스트 - 자바 편', '김종관', '2022');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! BERT와 GPT로 배우는 자연어 처리', '이기창', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 자바스크립트 입문', '고경희', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 첫 통계 with 베이즈', '사사키 준', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 딥러닝 교과서', '윤성진', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 자바 완전 정복', '김동형', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 인터랙티브 웹 페이지 만들기', '최성일', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 클론 코딩 트위터', '니꼴라스, 김준혁', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 안드로이드 앱 프로그래밍 - 개정 8판', '정재곤', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 리액트 네이티브 앱 프로그래밍', '전예홍', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 반응형 웹 페이지 만들기', '김운아', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 점프 투 장고', '박응용', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 쉽게 배우는 R 텍스트 마이닝', '김영우', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 장고+부트스트랩 파이썬 웹 개발의 정석', '이성용, 김태곤', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 첫 코딩 with 파이썬', '정동균', '2021');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 점프 투 플라스크', '박응용', '2020');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 프로그레시브 웹앱 만들기', '김응석', '2020');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 자료구조와 함께 배우는 알고리즘 입문 - 파이썬 편', '시바타 보요', '2020');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 클론 코딩 영화 평점 웹서비스', '니꼴라스, 김형태', '2020');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 건축 BIM을 위한 Revit 입문', '장동수', '2020');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 첫 파이썬', '엘리스 코딩', '2020');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 타입스크립트 프로그래밍', '전예홍', '2020');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! HTML5+CSS3 웹 표준의 정석 - 전면 개정 2판', '고경희', '2019');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 첫 코딩 with 자바', '정동균', '2019');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 정직하게 코딩하며 배우는 딥러닝 입문', '박해선', '2019');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 코틀린 프로그래밍', '황영덕', '2019');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! Vue.js 입문', '장기효', '2018');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! 쉽게 배우는 R 데이터 분석', '김영우', '2017');
INSERT INTO TBL_TEXTBOOK (TB_CODE, TB_NAME, TB_WRITER, TB_PUB_YEAR) VALUES (SEQ_TEXTBOOK.NEXTVAL, 'Do it! C 언어 입문', '김성엽', '2017');



-- ▣ 조회
SELECT *
FROM TBL_TEXTBOOK;

-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.