-- ▣ 테이블 생성
CREATE TABLE TBL_TEXTBOOK
(
  TB_CODE     NUMBER(6)  NOT NULL
, TB_NAME     VARCHAR2(32) NOT NULL
, TB_WRITER   VARCHAR2(32)
, TB_PUB_YEAR VARCHAR2(8)
, CONSTRAINT TBL_TEXTBOOK_PK PRIMARY KEY(TB_CODE)
);
-- ==> TBL_TEXTBOOK이(가) 생성되었습니다.


-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_TEXTBOOK IS '교재리스트_정적_테이블';
COMMENT ON COLUMN TBL_TEXTBOOK.TB_CODE IS '교재코드';
COMMENT ON COLUMN TBL_TEXTBOOK.TB_NAME IS '교재명';
COMMENT ON COLUMN TBL_TEXTBOOK.TB_WRITER IS '저자';
COMMENT ON COLUMN TBL_TEXTBOOK.TB_PUB_YEAR IS '발생년도';
-- ==>> Comment이(가) 생성되었습니다.


-- ▣ 테이블 삭제
-- DROP TABLE TBL_TEXTBOOK;