-- ▣ 테이블 삭제
-- DROP TABLE TBL_DROUP_OUT_STATUS;

-- ▣ 테이블 생성
CREATE TABLE TBL_DROUP_OUT_STATUS
(
  DOS_CODE NUMBER(8)    NOT NULL
, DOS_INFO VARCHAR2(128) NOT NULL
, CONSTRAINT TBL_DROUP_OUT_STATUS_PK PRIMARY KEY(DOS_CODE)
);
-- ==> TBL_DROUP_OUT_STATUS이(가) 생성되었습니다.

-- ▣ 컬럼 속성 변경
-- ALTER TABLE TBL_DROUP_OUT_STATUS MODIFY DOS_INFO VARCHAR2(128);

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_DROUP_OUT_STATUS IS '중도탈락상태_정적_테이블';
COMMENT ON COLUMN TBL_DROUP_OUT_STATUS.DOS_CODE IS '중도탈락상태코드';
COMMENT ON COLUMN TBL_DROUP_OUT_STATUS.DOS_INFO IS '중도탈락상세';
-- ==>> Comment이(가) 생성되었습니다.



-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_DOS
       INCREMENT BY 1
       START WITH 84000001
       MINVALUE 84000001
       MAXVALUE 85000000
       NOCYCLE
       NOCACHE
       NOORDER;
-- ==>> Sequence SEQ_DOS이(가) 생성되었습니다.



-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_DOS

-- ▣ 데이터 삭제
-- DELETE FROM TBL_DROUP_OUT_STATUS;

-- ▣ 데이터 입력
-- INSERT INTO TBL_DROUP_OUT_STATUS (DOS_CODE, DOS_INFO) VALUES (SEQ_DOS.NEXTVAL, ' ');
-- INSERT INTO TBL_DROUP_OUT_STATUS (DOS_CODE, DOS_INFO) VALUES (SEQ_DOS.NEXTVAL, '자진포기');
-- INSERT INTO TBL_DROUP_OUT_STATUS (DOS_CODE, DOS_INFO) VALUES (SEQ_DOS.NEXTVAL, '출석 기준 미달');
-- INSERT INTO TBL_DROUP_OUT_STATUS (DOS_CODE, DOS_INFO) VALUES (SEQ_DOS.NEXTVAL, '건강 문제');
-- INSERT INTO TBL_DROUP_OUT_STATUS (DOS_CODE, DOS_INFO) VALUES (SEQ_DOS.NEXTVAL, '해외 이주');
-- INSERT INTO TBL_DROUP_OUT_STATUS (DOS_CODE, DOS_INFO) VALUES (SEQ_DOS.NEXTVAL, '개인 사유');


-- ▣ 데이터 조회
SELECT *
FROM TBL_DROUP_OUT_STATUS;


-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.