-- ▣ 테이블 삭제
-- DROP TABLE TBL_DROUP_OUT_STATUS;

-- ▣ 테이블 생성
CREATE TABLE TBL_DROUP_OUT_STATUS
(
  DOS_CODE NUMBER(8)    NOT NULL
, DOS_INFO VARCHAR2(16) NOT NULL
, CONSTRAINT TBL_DROUP_OUT_STATUS_PK PRIMARY KEY(DOS_CODE)
);

-- ==> TBL_DROUP_OUT_STATUS이(가) 생성되었습니다.

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_DROUP_OUT_STATUS IS '중도탈락상태_정적_테이블';
COMMENT ON COLUMN TBL_DROUP_OUT_STATUS.DOS_CODE IS '중도탈락상태코드';
COMMENT ON COLUMN TBL_DROUP_OUT_STATUS.DOS_INFO IS '중도탈락상세';
-- ==>> Comment이(가) 생성되었습니다.



-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_DOS
       INCREMENT BY 1
       START WITH 84005001
       MINVALUE 84005001
       MAXVALUE 84006000
       NOCYCLE
       NOCACHE
       NOORDER;
-- ==>> Sequence SEQ_DOS이(가) 생성되었습니다.



-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_DOS



-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.