-- ▣ 테이블 삭제
-- DROP TABLE TBL_STUDENT;


-- ▣ 테이블 생성
CREATE TABLE TBL_STUDENT
(
  STUDENT_ID  NUMBER(6)    NOT NULL
, NAME        VARCHAR2(8)  NOT NULL
, SSN         VARCHAR2(14) NOT NULL
, LOGIN_ID    VARCHAR2(16)
, LOGIN_PW    VARCHAR2(16)
, ACTIVATE_YN CHAR(1)      DEFAULT 'Y' NOT NULL
, REG_DATE    DATE         DEFAULT SYSDATE NOT NULL
, CHG_DATE    DATE
, CONSTRAINT TBL_STUDENT_PK PRIMARY KEY(STUDENT_ID)
);
-- ==>>  Table TBL_STUDENT이(가) 생성되었습니다.


-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_STUDENT IS '학생';
COMMENT ON COLUMN TBL_STUDENT.STUDENT_ID IS '학생ID';
COMMENT ON COLUMN TBL_STUDENT.NAME IS '학생명';
COMMENT ON COLUMN TBL_STUDENT.SSN IS '주민번호';
COMMENT ON COLUMN TBL_STUDENT.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN TBL_STUDENT.LOGIN_PW IS '로그인PW';
COMMENT ON COLUMN TBL_STUDENT.ACTIVATE_YN IS '계정상태';
COMMENT ON COLUMN TBL_STUDENT.REG_DATE IS '학생등록일자';
COMMENT ON COLUMN TBL_STUDENT.CHG_DATE IS '정보변경일자';
-- ==>> Comment이(가) 생성되었습니다.

