-- ▣ 테이블 삭제
-- DROP TABLE TBL_STUDENT;


-- ▣ 테이블 생성
CREATE TABLE TBL_STUDENT
(
  STUDENT_ID  NUMBER(8)     NOT NULL
, NAME        VARCHAR2(16)  NOT NULL
, SSN         VARCHAR2(14)  NOT NULL
, LOGIN_ID    VARCHAR2(16)
, LOGIN_PW    VARCHAR2(16)
, ACTIVATE_YN CHAR(1)      DEFAULT 'Y' NOT NULL
, REG_DATE    DATE         DEFAULT SYSDATE NOT NULL
, CHG_DATE    DATE
, CONSTRAINT TBL_STUDENT_PK PRIMARY KEY(STUDENT_ID)
);
-- ==>>  Table TBL_STUDENT이(가) 생성되었습니다.

-- ▣ 컬럼 속성 변경
-- ALTER TABLE TBL_STUDENT MODIFY STUDENT_ID NUMBER(8);
-- ALTER TABLE TBL_STUDENT MODIFY NAME VARCHAR2(16);

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_STUDENT IS '학생';
COMMENT ON COLUMN TBL_STUDENT.STUDENT_ID IS '학생ID';
COMMENT ON COLUMN TBL_STUDENT.NAME IS '학생명';
COMMENT ON COLUMN TBL_STUDENT.SSN IS '주민번호';
COMMENT ON COLUMN TBL_STUDENT.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN TBL_STUDENT.LOGIN_PW IS '로그인PW';
COMMENT ON COLUMN TBL_STUDENT.ACTIVATE_YN IS '계정상태';
COMMENT ON COLUMN TBL_STUDENT.REG_DATE IS '학생등록일자';
COMMENT ON COLUMN TBL_STUDENT.CHG_DATE IS '정보변경일자';
-- ==>> Comment이(가) 생성되었습니다.

-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_STUDENT;

-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_STUDENT
       INCREMENT BY 1
       START WITH 20000001
       MINVALUE 20000001
       MAXVALUE 30000000
       NOCYCLE
       NOCACHE
       NOORDER;
-- ==>> Sequence SEQ_STUDENT이(가) 생성되었습니다.

-- 마보세  020617-2400287
-- 도건랑  020621-2308949
-- 방박위  011126-1718684
-- 주섭안  050303-2146578

-- ▣ 데이터 입력
INSERT INTO TBL_STUDENT (STUDENT_ID, NAME, SSN, ACTIVATE_YN) VALUES (SEQ_STUDENT.NEXTVAL, ' ', ' ', 'N');
INSERT INTO TBL_STUDENT (STUDENT_ID, NAME, SSN) VALUES (SEQ_STUDENT.NEXTVAL, '마보세', '020617-2400287');
INSERT INTO TBL_STUDENT (STUDENT_ID, NAME, SSN) VALUES (SEQ_STUDENT.NEXTVAL, '도건랑', '020621-2308949');
INSERT INTO TBL_STUDENT (STUDENT_ID, NAME, SSN) VALUES (SEQ_STUDENT.NEXTVAL, '방박위', '011126-1718684');
INSERT INTO TBL_STUDENT (STUDENT_ID, NAME, SSN) VALUES (SEQ_STUDENT.NEXTVAL, '주섭안', '050303-2146578');

-- ▣ 조회
SELECT *
FROM TBL_STUDENT;

-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.