-- ▣ 테이블 삭제
-- DROP TABLE TBL_LECTURER;


-- ▣ 테이블 생성
CREATE TABLE TBL_LECTURER
(
  LECTURER_ID NUMBER(6)    NOT NULL
, NAME        VARCHAR2(8)  NOT NULL
, SSN         VARCHAR2(14) NOT NULL
, LOGIN_ID    VARCHAR2(16)
, LOGIN_PW    VARCHAR2(16)
, ACTIVATE_YN CHAR(1)      DEFAULT 'Y' NOT NULL
, REG_DATE    DATE         DEFAULT SYSDATE NOT NULL
, CHG_DATE    DATE
, CONSTRAINT TBL_LECTURER_PK PRIMARY KEY (LECTURER_ID)
);
-- ==>> Table TBL_LECTURER이(가) 생성되었습니다. 

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_LECTURER IS '교수자';
COMMENT ON COLUMN TBL_LECTURER.LECTURER_ID IS '교수자ID';
COMMENT ON COLUMN TBL_LECTURER.NAME IS '교수자명';
COMMENT ON COLUMN TBL_LECTURER.SSN IS '주민번호';
COMMENT ON COLUMN TBL_LECTURER.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN TBL_LECTURER.LOGIN_PW IS '로그인PW';
COMMENT ON COLUMN TBL_LECTURER.ACTIVATE_YN IS '계정상태';
COMMENT ON COLUMN TBL_LECTURER.REG_DATE IS '등록일자';
COMMENT ON COLUMN TBL_LECTURER.CHG_DATE IS '변경일자';
-- ==>> Comment이(가) 생성되었습니다.
