-- ▣ 테이블 삭제
-- DROP TABLE TBL_LECTURER;


-- ▣ 테이블 생성
CREATE TABLE TBL_LECTURER
(
  LECTURER_ID NUMBER(8)    NOT NULL
, NAME        VARCHAR2(16)  NOT NULL
, SSN         VARCHAR2(14) NOT NULL
, LOGIN_ID    VARCHAR2(16)
, LOGIN_PW    VARCHAR2(16)
, ACTIVATE_YN CHAR(1)      DEFAULT 'Y' NOT NULL
, REG_DATE    DATE         DEFAULT SYSDATE NOT NULL
, CHG_DATE    DATE
, CONSTRAINT TBL_LECTURER_PK PRIMARY KEY (LECTURER_ID)
);
-- ==>> Table TBL_LECTURER이(가) 생성되었습니다. 

-- ▣ 컬럼 속성 변경
-- ALTER TABLE TBL_LECTURER MODIFY STUDENT_ID NUMBER(8);
-- ALTER TABLE TBL_LECTURER MODIFY NAME VARCHAR2(16);

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_LECTURER IS '교수자';
COMMENT ON COLUMN TBL_LECTURER.LECTURER_ID IS '교수자ID';
COMMENT ON COLUMN TBL_LECTURER.NAME IS '교수자명';
COMMENT ON COLUMN TBL_LECTURER.SSN IS '주민번호';
COMMENT ON COLUMN TBL_LECTURER.LOGIN_ID IS '로그인ID';
COMMENT ON COLUMN TBL_LECTURER.LOGIN_PW IS '로그인PW';
COMMENT ON COLUMN TBL_LECTURER.ACTIVATE_YN IS '계정상태';
COMMENT ON COLUMN TBL_LECTURER.REG_DATE IS '등록일자';
COMMENT ON COLUMN TBL_LECTURER.CHG_DATE IS '변경일자';
-- ==>> Comment이(가) 생성되었습니다.


-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_LECTURER
       INCREMENT BY 1
       START WITH 10000001
       MINVALUE 10000001
       MAXVALUE 20000000
       NOCYCLE
       NOCACHE
       NOORDER;


-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_LECTURER

-- ▣ 데이터 입력
-- INSERT INTO TBL_LECTURER (LECTURER_ID, NAME, SSN) 
-- VALUES (SEQ_LECTURER.NEXTVAL, '천소아', '610618-1074231');

-- INSERT INTO TBL_LECTURER (LECTURER_ID, NAME, SSN) 
-- VALUES (SEQ_LECTURER.NEXTVAL, '성악흔', '610901-1119898');

-- INSERT INTO TBL_LECTURER (LECTURER_ID, NAME, SSN) 
-- VALUES (SEQ_LECTURER.NEXTVAL, '왕춘나', '580613-2570960');

-- INSERT INTO TBL_LECTURER (LECTURER_ID, NAME, SSN) 
-- VALUES (SEQ_LECTURER.NEXTVAL, '주디설', '630525-1919563');
-- ==>> 1 행 이(가) 삽입되었습니다.

-- ▣ 조회
-- SELECT *
-- FROM TBL_LECTURER;

-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.