-- ▣ 테이블 삭제
-- DROP TABLE TBL_OFFERED_CURRICULUM;


-- ▣ 테이블 생성
CREATE TABLE TBL_OFFERED_CURRICULUM
(
  OCU_ID          NUMBER(8) NOT NULL
, OCU_SDATE       DATE
, OCU_EDATE       DATE
, OCU_SESSION     NUMBER    DEFAULT 1 NOT NULL
, OCU_STUD_MAX    NUMBER    DEFAULT 20 NOT NULL
, OCU_ACTIVATE_YN CHAR(1)   DEFAULT 'Y' NOT NULL
, CURRIC_CODE     NUMBER(8) NOT NULL
, CR_CODE         NUMBER(8) NOT NULL
, CONSTRAINT TBL_OFFERED_CURRICULUM_PK PRIMARY KEY (OCU_ID)
);
-- ==>> Table TBL_OFFERED_CURRICULUM이(가) 생성되었습니다.


-- ▣ 컬럼 속성 변경
-- ALTER TABLE TBL_OFFERED_CURRICULUM MODIFY OCU_STUD_MAX NUMBER DEFAULT 20;
-- DESC TBL_OFFERED_CURRICULUM;

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_OFFERED_CURRICULUM IS '개설과정';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_ID IS '과정ID';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_SDATE IS '과정시작';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_EDATE IS '과정종료';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_SESSION IS '과정회차';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_STUD_MAX IS '개설과정_정원';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_ACTIVATE_YN IS '과정상태';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.CURRIC_CODE IS '과정코드';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.CR_CODE IS '강의실코드';
-- ==>> Comment이(가) 생성되었습니다.


------------------[제약조건 추가]---------------------------
-- ▣ 제약조건(외래키) 추가
ALTER TABLE TBL_OFFERED_CURRICULUM
  ADD CONSTRAINT TBL_CLASSROOM_TO_OCU_FK
    FOREIGN KEY (CR_CODE)
    REFERENCES TBL_CLASSROOM (CR_CODE);
-- ==>> Table TBL_OFFERED_CURRICULUM이(가) 변경되었습니다.

-- ▣ 제약조건(외래키) 추가
ALTER TABLE TBL_OFFERED_CURRICULUM
  ADD CONSTRAINT TBL_CURRICULUM_TO_OCU_FK
    FOREIGN KEY (CURRIC_CODE)
    REFERENCES TBL_CURRICULUM (CURRIC_CODE);
-- ==>> Table TBL_OFFERED_CURRICULUM이(가) 변경되었습니다.

------------------[제약조건 삭제]---------------------------
-- ▣ 제약조건(외래키) 삭제
-- ALTER TABLE TBL_OFFERED_CURRICULUM
--   DROP CONSTRAINT TBL_CLASSROOM_TO_OCU_FK;

-- ALTER TABLE TBL_OFFERED_CURRICULUM
--   DROP CONSTRAINT TBL_CURRICULUM_TO_OCU_FK;



-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_OCU
       INCREMENT BY 1
       START WITH 30000001
       MINVALUE 30000001
       MAXVALUE 40000000
       NOCYCLE
       NOCACHE
       NOORDER;
-- ==>> Sequence SEQ_OCU이(가) 생성되었습니다.



-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_OCU

-- 오라클 AMPERSAND(&)등의 특수 문자 insert
SET DEFINE OFF;
SET DEFINE %;


--※ 날짜 관련 세션 설정 변경
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
-- ==>> Session이(가) 변경되었습니다.

-- ▣ 데이터 삭제
DELETE FROM TBL_OFFERED_CURRICULUM;

-- ▣ 데이터 입력
INSERT INTO TBL_OFFERED_CURRICULUM (OCU_ID, OCU_SESSION, OCU_STUD_MAX, OCU_ACTIVATE_YN, CURRIC_CODE, CR_CODE) 
VALUES (SEQ_OCU.NEXTVAL, 1, 1, 'N', 80000001, 85000001);

INSERT INTO TBL_OFFERED_CURRICULUM (OCU_ID, OCU_SDATE, OCU_EDATE, OCU_SESSION, OCU_STUD_MAX, CURRIC_CODE, CR_CODE) 
VALUES (SEQ_OCU.NEXTVAL, TO_DATE('2025-07-23', 'YYYY-MM-DD'), TO_DATE('2026-01-09', 'YYYY-MM-DD'), 1, 20, 80000002, 85000004);

INSERT INTO TBL_OFFERED_CURRICULUM (OCU_ID, OCU_SDATE, OCU_EDATE, OCU_SESSION, OCU_STUD_MAX, CURRIC_CODE, CR_CODE) 
VALUES (SEQ_OCU.NEXTVAL, TO_DATE('2025-08-24', 'YYYY-MM-DD'), TO_DATE('2026-03-09', 'YYYY-MM-DD'), 1, 20, 80000003, 85000014);


SELECT *
FROM 
(
  SELECT *
  FROM 
  (
      SELECT *
      FROM
      (
        SELECT *
        FROM TBL_OFFERED_CURRICULUM OCU JOIN TBL_CURRICULUM CURRIC
        USING(CURRIC_CODE)
      ) T
      -- WHERE T.CURRIC_CODE = 80000002
  ) T2 JOIN TBL_CLASSROOM C
  USING(CR_CODE)
) T3
-- WHERE T3.CR_CODE = 85000004;


-- ▣ 조회
SELECT *
FROM TBL_OFFERED_CURRICULUM;
-- WHERE OCU_EDATE IS NULL;

-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.