-- ▣ 테이블 삭제
-- DROP TABLE TBL_OFFERED_CURRICULUM;


-- ▣ 테이블 생성
CREATE TABLE TBL_OFFERED_CURRICULUM
(
  OCU_ID          NUMBER(6) NOT NULL
, OCU_SDATE       DATE
, OCU_EDATE       DATE
, OCU_SESSION     NUMBER    DEFAULT 1 NOT NULL
, OCU_STUD_MAX    NUMBER    DEFAULT 10 NOT NULL
, OCU_ACTIVATE_YN CHAR(1)   DEFAULT 'Y' NOT NULL
, CURRIC_CODE     NUMBER(6)
, CR_CODE         NUMBER(6) NOT NULL
, CONSTRAINT TBL_OFFERED_CURRICULUM_PK PRIMARY KEY (OCU_ID)
);
-- ==>> Table TBL_OFFERED_CURRICULUM이(가) 생성되었습니다.


-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_OFFERED_CURRICULUM IS '개설과정';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_ID IS '과정ID';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_SDATE IS '과정시작';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_EDATE IS '과정종료';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_SESSION IS '과정회차';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_STUD_MAX IS '개설과정_정원';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.OCU_ACTIVATE_YN IS '과정상태';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.CURRIC_CODE IS '과정코드';
COMMENT ON COLUMN TBL_OFFERED_CURRICULUM.CR_CODE IS '강의실코드';
-- ==>> Comment이(가) 생성되었습니다.


------------------[제약조건 추가]---------------------------
-- ▣ 제약조건(외래키) 추가
ALTER TABLE TBL_OFFERED_CURRICULUM
  ADD CONSTRAINT FK_TBL_CLASSROOM_TO_OCU
    FOREIGN KEY (CR_CODE)
    REFERENCES TBL_CLASSROOM (CR_CODE);
-- ==>> Table TBL_OFFERED_CURRICULUM이(가) 변경되었습니다.

-- ▣ 제약조건(외래키) 추가
ALTER TABLE TBL_OFFERED_CURRICULUM
  ADD CONSTRAINT FK_TBL_CURRICULUM_TO_OCU
    FOREIGN KEY (CURRIC_CODE)
    REFERENCES TBL_CURRICULUM (CURRIC_CODE);
-- ==>> Table TBL_OFFERED_CURRICULUM이(가) 변경되었습니다.

------------------[제약조건 삭제]---------------------------
-- ▣ 제약조건(외래키) 삭제
-- ALTER TABLE TBL_OFFERED_CURRICULUM
--   DROP CONSTRAINT FK_TBL_CLASSROOM_TO_OCU;

-- ALTER TABLE TBL_OFFERED_CURRICULUM
--   DROP CONSTRAINT FK_TBL_CURRICULUM_TO_OCU;