-- ▣ 테이블 삭제
-- DROP TABLE TBL_OFFERED_COURSE;


-- ▣ 테이블 생성
CREATE TABLE TBL_OFFERED_COURSE
(
  OCO_ID         NUMBER(6) NOT NULL
, OCO_SDATE      DATE      NOT NULL
, OCO_EDATE      DATE      NOT NULL
, OCO_WGT_WT     NUMBER(2) NOT NULL
, OCO_WGT_PT     NUMBER(2) NOT NULL
, OCO_WGT_ATTEND NUMBER(2) NOT NULL
, OCU_ID         NUMBER(6) NOT NULL
, SUBJ_CODE      NUMBER(6) NOT NULL
, TB_CODE        NUMBER(6) NOT NULL
, LECTURER_ID    NUMBER(6) NOT NULL
, CONSTRAINT PK_TBL_OFFERED_COURSE PRIMARY KEY (OCO_ID)
);
-- ==>> Table TBL_OFFERED_COURSE이(가) 생성되었습니다.

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_OFFERED_COURSE IS '개설과목';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_ID IS '과목ID';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_SDATE IS '과목기간_시작';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_EDATE IS '과목기간_종료';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_WGT_WT IS '필기배점';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_WGT_PT IS '실기배점';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_WGT_ATTEND IS '출결배점';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCU_ID IS '과정ID';
COMMENT ON COLUMN TBL_OFFERED_COURSE.SUBJ_CODE IS '과목코드';
COMMENT ON COLUMN TBL_OFFERED_COURSE.TB_CODE IS '교재코드';
COMMENT ON COLUMN TBL_OFFERED_COURSE.LECTURER_ID IS '교수자ID';
-- ==>> Comment이(가) 생성되었습니다.
