-- ▣ 테이블 삭제
-- DROP TABLE TBL_OFFERED_COURSE;


-- ▣ 테이블 생성
CREATE TABLE TBL_OFFERED_COURSE
(
  OCO_ID         NUMBER(8) NOT NULL
, OCO_SDATE      DATE      NOT NULL
, OCO_EDATE      DATE      NOT NULL
, OCO_WGT_WT     NUMBER(3) DEFAULT 35 NOT NULL
, OCO_WGT_PT     NUMBER(3) DEFAULT 35 NOT NULL
, OCO_WGT_ATTEND NUMBER(3) DEFAULT 30 NOT NULL
, OCU_ID         NUMBER(8) NOT NULL
, SUBJ_CODE      NUMBER(8) NOT NULL
, TB_CODE        NUMBER(8) NOT NULL
, LECTURER_ID    NUMBER(8) NOT NULL
, CONSTRAINT PK_TBL_OFFERED_COURSE PRIMARY KEY (OCO_ID)
);
-- ==>> Table TBL_OFFERED_COURSE이(가) 생성되었습니다.


-- ▣ 컬럼 속성 변경
-- ALTER TABLE TBL_OFFERED_COURSE MODIFY OCO_WGT_WT NUMBER(3);
-- ALTER TABLE TBL_OFFERED_COURSE MODIFY OCO_WGT_PT NUMBER(3);
-- ALTER TABLE TBL_OFFERED_COURSE MODIFY OCO_WGT_ATTEND NUMBER(3);
-- DESC TBL_OFFERED_COURSE;

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_OFFERED_COURSE IS '개설과목';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_ID IS '과목ID';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_SDATE IS '과목기간_시작';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_EDATE IS '과목기간_종료';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_WGT_WT IS '필기배점';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_WGT_PT IS '실기배점';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_WGT_ATTEND IS '출결배점';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCU_ID IS '과정ID';
COMMENT ON COLUMN TBL_OFFERED_COURSE.SUBJ_CODE IS '과목코드';
COMMENT ON COLUMN TBL_OFFERED_COURSE.TB_CODE IS '교재코드';
COMMENT ON COLUMN TBL_OFFERED_COURSE.LECTURER_ID IS '교수자ID';
-- ==>> Comment이(가) 생성되었습니다.

------------------[제약조건 추가]---------------------------
-- ▣ 제약조건(외래키) 추가
ALTER TABLE TBL_OFFERED_COURSE
  ADD CONSTRAINT TEXTBOOK_TO_OFFERED_COURSE_FK
    FOREIGN KEY (TB_CODE)
    REFERENCES TBL_TEXTBOOK (TB_CODE);
-- ==>> Table TBL_OFFERED_COURSE이(가) 변경되었습니다.

ALTER TABLE TBL_OFFERED_COURSE
  ADD CONSTRAINT SUBJECT_TO_OFFERED_COURSE_FK
    FOREIGN KEY (SUBJ_CODE)
    REFERENCES TBL_SUBJECT (SUBJ_CODE);
-- ==>> Table TBL_OFFERED_COURSE이(가) 변경되었습니다.

ALTER TABLE TBL_OFFERED_COURSE
  ADD CONSTRAINT OCU_TO_OFFERED_COURSE_FK
    FOREIGN KEY (OCU_ID)
    REFERENCES TBL_OFFERED_CURRICULUM (OCU_ID);
-- ==>> Table TBL_OFFERED_COURSE이(가) 변경되었습니다.


ALTER TABLE TBL_OFFERED_COURSE
  ADD CONSTRAINT LECTURER_TO_OFFERED_COURSE_FK
    FOREIGN KEY (LECTURER_ID)
    REFERENCES TBL_LECTURER (LECTURER_ID);
-- ==>> Table TBL_OFFERED_COURSE이(가) 변경되었습니다.


------------------[제약조건 삭제]---------------------------
-- ▣ 제약조건(외래키) 삭제
-- ALTER TABLE TBL_OFFERED_COURSE
--   DROP CONSTRAINT TEXTBOOK_TO_OFFERED_COURSE_FK;

-- ALTER TABLE TBL_OFFERED_COURSE
--   DROP CONSTRAINT SUBJECT_TO_OFFERED_COURSE_FK;

-- ALTER TABLE TBL_OFFERED_COURSE
--   DROP CONSTRAINT OCU_TO_OFFERED_COURSE_FK;

-- ALTER TABLE TBL_OFFERED_COURSE
--   DROP CONSTRAINT LECTURER_TO_OFFERED_COURSE_FK;



-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_OC
       INCREMENT BY 1
       START WITH 40000001
       MINVALUE 40000001
       MAXVALUE 50000000
       NOCYCLE
       NOCACHE
       NOORDER;
-- ==>> Sequence SEQ_OC이(가) 생성되었습니다.


-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_OC

-- ▣ 데이터 삭제
DELETE FROM TBL_OFFERED_COURSE;

-- 오라클 AMPERSAND(&)등의 특수 문자 insert
SET DEFINE OFF;
SET DEFINE %;

-- ▣ 데이터 입력[CURRIC_CODE = 80000001]
INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('1900-01-01', 'YYYY-MM-DD'), TO_DATE('1900-01-01', 'YYYY-MM-DD'), 30000001, 73000001, 74000001, 10000001);


-- ▣ 데이터 입력[CURRIC_CODE = 80000002]
-- ▣ 조회
SELECT *
FROM TBL_CURRICULUM CURR, TBL_OFFERED_CURRICULUM OCU
WHERE CURR.CURRIC_CODE = OCU.CURRIC_CODE
  AND OCU.CURRIC_CODE = 80000002;

---------------------
SELECT *
FROM TBL_SUBJECT
WHERE TBL_SUBJECT.SUBJ_NAME = 'Python프로그래밍기초';

SELECT *
FROM TBL_TEXTBOOK
WHERE TBL_TEXTBOOK.TB_NAME LIKE '%파이썬%';

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-07-23', 'YYYY-MM-DD'), TO_DATE('2026-01-09', 'YYYY-MM-DD'), 40, 40, 20, 30000002, 73000087, 74000036, 10000002);

--------------------
SELECT *
FROM TBL_SUBJECT
WHERE TBL_SUBJECT.SUBJ_NAME = '파이썬';

SELECT *
FROM TBL_TEXTBOOK
WHERE TBL_TEXTBOOK.TB_NAME LIKE '%챗GPT%';

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-08-23', 'YYYY-MM-DD'), TO_DATE('2026-01-09', 'YYYY-MM-DD'), 40, 40, 20, 30000002, 73000649, 74000086, 10000002);

--------------------
SELECT *
FROM TBL_SUBJECT
WHERE TBL_SUBJECT.SUBJ_NAME LIKE '%자바 웹 개발%';

SELECT *
FROM TBL_TEXTBOOK
WHERE TBL_TEXTBOOK.TB_NAME LIKE '%자바 웹 개발 워크북%';

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-08-23', 'YYYY-MM-DD'), TO_DATE('2026-01-09', 'YYYY-MM-DD'), 40, 40, 20, 30000002, 73000650, 74000087, 10000002);

--------------------
SELECT *
FROM TBL_SUBJECT
WHERE UPPER(TBL_SUBJECT.SUBJ_NAME) LIKE UPPER('%sql%');

SELECT *
FROM TBL_TEXTBOOK
WHERE UPPER(TBL_TEXTBOOK.TB_NAME) LIKE UPPER('%Do it! SQL 입문%');

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-08-23', 'YYYY-MM-DD'), TO_DATE('2026-01-09', 'YYYY-MM-DD'), 40, 40, 20, 30000002, 73000651, 74000088, 10000002);

--------------------
SELECT *
FROM TBL_SUBJECT
WHERE UPPER(TBL_SUBJECT.SUBJ_NAME) LIKE UPPER('%jsp%');
SELECT *
FROM TBL_TEXTBOOK
WHERE UPPER(TBL_TEXTBOOK.TB_NAME) LIKE UPPER('백견불여일타 JSP & Servlet : Oracle & Eclipse(2025)');

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-09-23', 'YYYY-MM-DD'), TO_DATE('2026-01-09', 'YYYY-MM-DD'), 40, 40, 20, 30000002, 73000082, 74000089, 10000002);

--------------------
SET DEFINE OFF;
SET DEFINE %;

SELECT *
FROM TBL_SUBJECT
WHERE UPPER(TBL_SUBJECT.SUBJ_NAME) LIKE UPPER('리액트');

SELECT *
FROM TBL_TEXTBOOK
WHERE UPPER(TBL_TEXTBOOK.TB_NAME) LIKE UPPER('코드로 배우는 리액트(2025)');
-- WHERE UPPER(TBL_TEXTBOOK.TB_NAME) LIKE UPPER('%백견불여일타 JSP & Servlet : Oracle & Eclipse(2025)%');

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-11-23', 'YYYY-MM-DD'), TO_DATE('2026-01-09', 'YYYY-MM-DD'), 40, 40, 20, 30000002,   73000653, 74000090, 10000002);

-----------------------
-- ▣ 데이터 입력[CURRIC_CODE = 80000003]
-- ▣ 조회
SELECT *
FROM TBL_CURRICULUM CURR, TBL_OFFERED_CURRICULUM OCU
WHERE CURR.CURRIC_CODE = OCU.CURRIC_CODE
  AND OCU.CURRIC_CODE = 80000003;

---------------------
SET DEFINE OFF;
SET DEFINE %;

SELECT *
FROM TBL_SUBJECT
WHERE UPPER(TBL_SUBJECT.SUBJ_NAME) LIKE UPPER('Python : 머신러닝');

SELECT *
FROM TBL_TEXTBOOK
WHERE UPPER(TBL_TEXTBOOK.TB_NAME) LIKE UPPER('파이썬 머신러닝 완벽 가이드(개정2판)');

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-08-24', 'YYYY-MM-DD'), TO_DATE('2025-09-24', 'YYYY-MM-DD'), 40, 20, 40, 80000003,   73000654, 74000091, 10000003);
---------------------
SET DEFINE OFF;
SET DEFINE %;

SELECT *
FROM TBL_SUBJECT
WHERE UPPER(TBL_SUBJECT.SUBJ_NAME) LIKE UPPER('Python : 딥러닝');

SELECT *
FROM TBL_TEXTBOOK
WHERE UPPER(TBL_TEXTBOOK.TB_NAME) LIKE UPPER('모두의 딥러닝 개정3판');

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-08-24', 'YYYY-MM-DD'), TO_DATE('2025-09-24', 'YYYY-MM-DD'), 40, 20, 40, 80000003,   73000655, 74000092, 10000003);
---------------------
SET DEFINE OFF;
SET DEFINE %;

SELECT *
FROM TBL_SUBJECT
WHERE UPPER(TBL_SUBJECT.SUBJ_NAME) LIKE UPPER('Back End 설계와 응용');

SELECT *
FROM TBL_TEXTBOOK
WHERE UPPER(TBL_TEXTBOOK.TB_NAME) LIKE UPPER('Node.js 교과서');

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-08-24', 'YYYY-MM-DD'), TO_DATE('2025-09-24', 'YYYY-MM-DD'), 40, 20, 40, 80000003,   73000656, 74000093, 10000003);
---------------------
SET DEFINE OFF;
SET DEFINE %;

SELECT *
FROM TBL_SUBJECT
WHERE UPPER(TBL_SUBJECT.SUBJ_NAME) LIKE UPPER('Python');

SELECT *
FROM TBL_TEXTBOOK
WHERE UPPER(TBL_TEXTBOOK.TB_NAME) LIKE UPPER('내일은 파이썬');

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-08-24', 'YYYY-MM-DD'), TO_DATE('2025-09-24', 'YYYY-MM-DD'), 40, 20, 40, 80000003,   73000657, 74000094, 10000003);
---------------------
SET DEFINE OFF;
SET DEFINE %;

SELECT *
FROM TBL_SUBJECT
WHERE UPPER(TBL_SUBJECT.SUBJ_NAME) LIKE UPPER('앱 개발 : Flutter');

SELECT *
FROM TBL_TEXTBOOK
WHERE UPPER(TBL_TEXTBOOK.TB_NAME) LIKE UPPER('내일은 플러터');

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-08-24', 'YYYY-MM-DD'), TO_DATE('2025-09-24', 'YYYY-MM-DD'), 40, 20, 40, 80000003,   73000658, 74000095, 10000003);
---------------------
SET DEFINE OFF;
SET DEFINE %;

SELECT *
FROM TBL_SUBJECT
WHERE UPPER(TBL_SUBJECT.SUBJ_NAME) LIKE UPPER('정형 데이터 관리 및 처리(Oracle, SQL)');

SELECT *
FROM TBL_TEXTBOOK
WHERE UPPER(TBL_TEXTBOOK.TB_NAME) LIKE UPPER('2025 내일은 SQL 개발자');

INSERT INTO TBL_OFFERED_COURSE (OCO_ID, OCO_SDATE, OCO_EDATE, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCU_ID, SUBJ_CODE, TB_CODE, LECTURER_ID) 
VALUES (SEQ_OC.NEXTVAL, TO_DATE('2025-08-24', 'YYYY-MM-DD'), TO_DATE('2025-09-24', 'YYYY-MM-DD'), 40, 20, 40, 80000003,   73000659, 74000096, 10000003);
-----------------------
-- ▣ 데이터 변경[CURRIC_CODE = 80000003]
-- ▣ UPDATE
-- 조회
SELECT *
FROM TBL_OFFERED_COURSE
WHERE LECTURER_ID  = 10000003;

-- UPDATE
UPDATE TBL_OFFERED_COURSE
SET OCU_ID = 30000003
WHERE LECTURER_ID  = 10000003;
---------------------------------------------------------
-- ▣ 전체 데이터 조회
SELECT *
FROM 
(
  SELECT *
  FROM 
  (
    SELECT *
    FROM 
    (
      SELECT *
      FROM 
      (
          SELECT *
          FROM
          (
            SELECT *
            FROM TBL_OFFERED_COURSE OC JOIN TBL_OFFERED_CURRICULUM OCU
            USING(OCU_ID)
          ) T
          -- WHERE T.CURRIC_CODE = 80000002
      ) T2 JOIN TBL_SUBJECT S
      USING(SUBJ_CODE)
    ) T3 JOIN TBL_TEXTBOOK TB
    USING(TB_CODE)
  ) T4 JOIN TBL_LECTURER L
  USING(LECTURER_ID)
) T5 JOIN TBL_CURRICULUM CURRIC
USING(CURRIC_CODE)
WHERE T5.OCU_ID = 30000003
ORDER BY T5.SUBJ_CODE;



-- ▣ 데이터 조회
SELECT *
FROM TBL_OFFERED_COURSE;

-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.