-- ▣ 테이블 삭제
-- DROP TABLE TBL_OFFERED_COURSE;


-- ▣ 테이블 생성
CREATE TABLE TBL_OFFERED_COURSE
(
  OCO_ID         NUMBER(8) NOT NULL
, OCO_SDATE      DATE      NOT NULL
, OCO_EDATE      DATE      NOT NULL
, OCO_WGT_WT     NUMBER(2) NOT NULL
, OCO_WGT_PT     NUMBER(2) NOT NULL
, OCO_WGT_ATTEND NUMBER(2) NOT NULL
, OCU_ID         NUMBER(8) NOT NULL
, SUBJ_CODE      NUMBER(8) NOT NULL
, TB_CODE        NUMBER(8) NOT NULL
, LECTURER_ID    NUMBER(8) NOT NULL
, CONSTRAINT PK_TBL_OFFERED_COURSE PRIMARY KEY (OCO_ID)
);
-- ==>> Table TBL_OFFERED_COURSE이(가) 생성되었습니다.

-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_OFFERED_COURSE IS '개설과목';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_ID IS '과목ID';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_SDATE IS '과목기간_시작';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_EDATE IS '과목기간_종료';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_WGT_WT IS '필기배점';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_WGT_PT IS '실기배점';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCO_WGT_ATTEND IS '출결배점';
COMMENT ON COLUMN TBL_OFFERED_COURSE.OCU_ID IS '과정ID';
COMMENT ON COLUMN TBL_OFFERED_COURSE.SUBJ_CODE IS '과목코드';
COMMENT ON COLUMN TBL_OFFERED_COURSE.TB_CODE IS '교재코드';
COMMENT ON COLUMN TBL_OFFERED_COURSE.LECTURER_ID IS '교수자ID';
-- ==>> Comment이(가) 생성되었습니다.

------------------[제약조건 추가]---------------------------
-- ▣ 제약조건(외래키) 추가
ALTER TABLE TBL_OFFERED_COURSE
  ADD CONSTRAINT TEXTBOOK_TO_OFFERED_COURSE_FK
    FOREIGN KEY (TB_CODE)
    REFERENCES TBL_TEXTBOOK (TB_CODE);
-- ==>> Table TBL_OFFERED_COURSE이(가) 변경되었습니다.

ALTER TABLE TBL_OFFERED_COURSE
  ADD CONSTRAINT SUBJECT_TO_OFFERED_COURSE_FK
    FOREIGN KEY (SUBJ_CODE)
    REFERENCES TBL_SUBJECT (SUBJ_CODE);
-- ==>> Table TBL_OFFERED_COURSE이(가) 변경되었습니다.

ALTER TABLE TBL_OFFERED_COURSE
  ADD CONSTRAINT OCU_TO_OFFERED_COURSE_FK
    FOREIGN KEY (OCU_ID)
    REFERENCES TBL_OFFERED_CURRICULUM (OCU_ID);
-- ==>> Table TBL_OFFERED_COURSE이(가) 변경되었습니다.


ALTER TABLE TBL_OFFERED_COURSE
  ADD CONSTRAINT LECTURER_TO_OFFERED_COURSE_FK
    FOREIGN KEY (LECTURER_ID)
    REFERENCES TBL_LECTURER (LECTURER_ID);
-- ==>> Table TBL_OFFERED_COURSE이(가) 변경되었습니다.


------------------[제약조건 삭제]---------------------------
-- ▣ 제약조건(외래키) 삭제
-- ALTER TABLE TBL_OFFERED_COURSE
--   DROP CONSTRAINT TEXTBOOK_TO_OFFERED_COURSE_FK;

-- ALTER TABLE TBL_OFFERED_COURSE
--   DROP CONSTRAINT SUBJECT_TO_OFFERED_COURSE_FK;

-- ALTER TABLE TBL_OFFERED_COURSE
--   DROP CONSTRAINT OCU_TO_OFFERED_COURSE_FK;

-- ALTER TABLE TBL_OFFERED_COURSE
--   DROP CONSTRAINT LECTURER_TO_OFFERED_COURSE_FK;



-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_OC
       INCREMENT BY 1
       START WITH 40000001
       MINVALUE 40000001
       MAXVALUE 50000000
       NOCYCLE
       NOCACHE
       NOORDER;
-- ==>> Sequence SEQ_OC이(가) 생성되었습니다.


-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_OC


-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.