-- ▣ 테이블 삭제
-- DROP TABLE TBL_REG_COURSE;


-- ▣ 테이블 생성
CREATE TABLE TBL_REG_COURSE
(
  RC_ID      NUMBER(6) NOT NULL
, STUDENT_ID NUMBER(6) NOT NULL
, OCU_ID     NUMBER(6) NOT NULL
, REG_DATE   DATE      DEFAULT SYSDATE NOT NULL
, CONSTRAINT TBL_REG_COURSE_PK PRIMARY KEY (RC_ID)
);
-- ==>> Table TBL_REG_COURSE이(가) 생성되었습니다.


-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_REG_COURSE IS '수강등록리스트';
COMMENT ON COLUMN TBL_REG_COURSE.RC_ID IS '수강등록ID';
COMMENT ON COLUMN TBL_REG_COURSE.STUDENT_ID IS '학생ID';
COMMENT ON COLUMN TBL_REG_COURSE.OCU_ID IS '개설과정ID';
COMMENT ON COLUMN TBL_REG_COURSE.REG_DATE IS '수강등록일자';
-- ==>> Comment이(가) 생성되었습니다.


------------------[제약조건 추가]---------------------------
-- ▣ 제약조건(외래키) 추가
ALTER TABLE TBL_REG_COURSE
  ADD CONSTRAINT FK_STUDENT_TO_REG_COURSE
    FOREIGN KEY (STUDENT_ID)
    REFERENCES TBL_STUDENT (STUDENT_ID);
--  ==>> Table TBL_REG_COURSE이(가) 변경되었습니다.


ALTER TABLE TBL_REG_COURSE
  ADD CONSTRAINT FK_OCU_TO_REG_COURSE
    FOREIGN KEY (OCU_ID)
    REFERENCES TBL_OFFERED_CURRICULUM (OCU_ID);
-- ==>> Table TBL_REG_COURSE이(가) 변경되었습니다.


------------------[제약조건 삭제]---------------------------
-- ▣ 제약조건(외래키) 삭제
-- ALTER TABLE TBL_REG_COURSE
--   DROP CONSTRAINT FK_STUDENT_TO_REG_COURSE;

-- ALTER TABLE TBL_REG_COURSE
--   DROP CONSTRAINT FK_OCU_TO_REG_COURSE;