-- ▣ 테이블 삭제
-- DROP TABLE TBL_SCORE;


-- ▣ 테이블 생성
CREATE TABLE TBL_SCORE
(
  SCORE_ID     NUMBER(6) NOT NULL
, SCORE_WT     NUMBER(3)
, SCORE_PT     NUMBER(3)
, SCORE_ATTEND NUMBER(3)
, RC_ID        NUMBER(6) NOT NULL
, OCO_ID       NUMBER(6) NOT NULL
, REG_DATE     DATE      DEFAULT SYSDATE NOT NULL
, CONSTRAINT TBL_SCORE_PK PRIMARY KEY (SCORE_ID)
);
-- ==>> Table TBL_SCORE이(가) 생성되었습니다.


-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_SCORE IS '성적';
COMMENT ON COLUMN TBL_SCORE.SCORE_ID IS '성적ID';
COMMENT ON COLUMN TBL_SCORE.SCORE_WT IS '필기_점수';
COMMENT ON COLUMN TBL_SCORE.SCORE_PT IS '실기_점수';
COMMENT ON COLUMN TBL_SCORE.SCORE_ATTEND IS '출결_점수';
COMMENT ON COLUMN TBL_SCORE.RC_ID IS '수강등록ID';
COMMENT ON COLUMN TBL_SCORE.OCO_ID IS '개설과목ID';
COMMENT ON COLUMN TBL_SCORE.REG_DATE IS '성적등록일자';

-- ==>> Comment이(가) 생성되었습니다.


------------------[제약조건 추가]---------------------------
-- ▣ 제약조건(외래키) 추가
ALTER TABLE TBL_SCORE
  ADD CONSTRAINT FK_OFFERED_COURSE_TO_SCORE
    FOREIGN KEY (OCO_ID)
    REFERENCES TBL_OFFERED_COURSE (OCO_ID);
-- ==>> Table TBL_SCORE이(가) 변경되었습니다.

ALTER TABLE TBL_SCORE
  ADD CONSTRAINT FK_REG_COURSE_TO_SCORE
    FOREIGN KEY (RC_ID)
    REFERENCES TBL_REG_COURSE (RC_ID);
-- ==>> Table TBL_SCORE이(가) 변경되었습니다.

------------------[제약조건 삭제]---------------------------
-- ▣ 제약조건(외래키) 삭제
-- ALTER TABLE TBL_SCORE
--   DROP CONSTRAINT FK_OFFERED_COURSE_TO_SCORE;

-- ALTER TABLE TBL_SCORE
--   DROP CONSTRAINT FK_REG_COURSE_TO_SCORE;