-- ▣ 테이블 삭제
-- DROP TABLE TBL_SCORE;


-- ▣ 테이블 생성
CREATE TABLE TBL_SCORE
(
  SCORE_ID     NUMBER(8) NOT NULL
, SCORE_WT     NUMBER(3)
, SCORE_PT     NUMBER(3)
, SCORE_ATTEND NUMBER(3)
, RC_ID        NUMBER(8) NOT NULL
, OCO_ID       NUMBER(8) NOT NULL
, REG_DATE     DATE      DEFAULT SYSDATE NOT NULL
, CONSTRAINT TBL_SCORE_PK PRIMARY KEY (SCORE_ID)
);
-- ==>> Table TBL_SCORE이(가) 생성되었습니다.


-- ▣ 컬럼 코멘트 추가
COMMENT ON TABLE TBL_SCORE IS '성적';
COMMENT ON COLUMN TBL_SCORE.SCORE_ID IS '성적ID';
COMMENT ON COLUMN TBL_SCORE.SCORE_WT IS '필기_점수';
COMMENT ON COLUMN TBL_SCORE.SCORE_PT IS '실기_점수';
COMMENT ON COLUMN TBL_SCORE.SCORE_ATTEND IS '출결_점수';
COMMENT ON COLUMN TBL_SCORE.RC_ID IS '수강등록ID';
COMMENT ON COLUMN TBL_SCORE.OCO_ID IS '개설과목ID';
COMMENT ON COLUMN TBL_SCORE.REG_DATE IS '성적등록일자';

-- ==>> Comment이(가) 생성되었습니다.


------------------[제약조건 추가]---------------------------
-- ▣ 제약조건(외래키) 추가
ALTER TABLE TBL_SCORE
  ADD CONSTRAINT OFFERED_COURSE_TO_SCORE_FK
    FOREIGN KEY (OCO_ID)
    REFERENCES TBL_OFFERED_COURSE (OCO_ID);
-- ==>> Table TBL_SCORE이(가) 변경되었습니다.

ALTER TABLE TBL_SCORE
  ADD CONSTRAINT REG_COURSE_TO_SCORE_FK
    FOREIGN KEY (RC_ID)
    REFERENCES TBL_REG_COURSE (RC_ID);
-- ==>> Table TBL_SCORE이(가) 변경되었습니다.

------------------[제약조건 삭제]---------------------------
-- ▣ 제약조건(외래키) 삭제
-- ALTER TABLE TBL_SCORE
--   DROP CONSTRAINT OFFERED_COURSE_TO_SCORE_FK;

-- ALTER TABLE TBL_SCORE
--   DROP CONSTRAINT REG_COURSE_TO_SCORE_FK;


-- ▣ 시퀀스 추가
CREATE SEQUENCE SEQ_SCORE
       INCREMENT BY 1
       START WITH 60000001
       MINVALUE 60000001
       MAXVALUE 70000000
       NOCYCLE
       NOCACHE
       NOORDER;
-- ==>> Sequence SEQ_SCORE이(가) 생성되었습니다.


-- ▣ 시퀀스 삭제
-- DROP SEQUENCE SEQ_SCORE


-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.

-----------------------------------------------------------------
DESC TBL_SCORE;

SELECT *
FROM TBL_SCORE;

SELECT *
FROM TBL_OFFERED_COURSE;

SELECT *
FROM TBL_REG_COURSE;

SELECT *
FROM TBL_DROUP_OUT;


SELECT *
FROM TBL_LECTURER
WHERE LECTURER_ID = 10000002
ORDER BY LECTURER_ID;

---------------------------------------------
CREATE OR REPLACE VIEW VIEW_TEST_SCORE AS
-- SELECT STUDENT_ID, OCO_WGT_WT, OCO_WGT_PT, OCO_WGT_ATTEND, OCO_ID, RC_ID, SUBJ_CODE, DO_ID
SELECT *
FROM
(
  SELECT *
  FROM
  (
    SELECT *
    FROM
    (
      SELECT *
      FROM
      (
        SELECT *
        FROM
        (
          SELECT *
          FROM TBL_OFFERED_COURSE OC JOIN  TBL_LECTURER LL
          USING(LECTURER_ID)
          WHERE LECTURER_ID = 10000002
        ) T1 JOIN TBL_SUBJECT SUBJ
        USING(SUBJ_CODE)
      ) T2 JOIN TBL_OFFERED_CURRICULUM OCU
      USING(OCU_ID)
      WHERE OCU_ID = 30000002
    ) T3 JOIN TBL_REG_COURSE RC
    USING(OCU_ID)
  ) T4 JOIN TBL_STUDENT STUD
  USING(STUDENT_ID)
) T5 LEFT JOIN TBL_DROUP_OUT DO
USING (RC_ID)
WHERE SUBJ_CODE = 73000087;

----TEST VIEW ---
SELECT *
FROM VIEW_TEST_SCORE;


---- 성적 입력
INSERT INTO MIRACLE.TBL_SCORE (SCORE_ID, SCORE_WT, SCORE_PT, SCORE_ATTEND, RC_ID, OCO_ID) VALUES (MIRACLE.SEQ_SCORE.NEXTVAL, TRUNC(890*0.4), TRUNC(670*0.4), TRUNC(100*0.2), 50000015, 40000002);
INSERT INTO MIRACLE.TBL_SCORE (SCORE_ID, SCORE_WT, SCORE_PT, SCORE_ATTEND, RC_ID, OCO_ID) VALUES (MIRACLE.SEQ_SCORE.NEXTVAL, TRUNC(890*0.4), TRUNC(670*0.4), TRUNC(100*0.2), 50000017, 40000002);

-- ▣ 커밋
COMMIT;

SELECT TRUNC(100*0.4), TRUNC(100*0.4), TRUNC(100*0.2)
FROM DUAL;

SELECT *
FROM TBL_SCORE;


-----------------------------------------------------------------
-- ▣ 커밋
-- COMMIT;
-- ==>> 커밋 완료.
-----------------------------------------------------------------
