/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import com.google.gson.Gson;
import org.example.vo.Todo;

import org.tensorflow.ConcreteFunction;
import org.tensorflow.Signature;
import org.tensorflow.Tensor;
import org.tensorflow.TensorFlow;
import org.tensorflow.op.Ops;
import org.tensorflow.op.core.Placeholder;
import org.tensorflow.op.math.Add;
import org.tensorflow.types.TInt32;

/**
 * The main application class.
 * This class contains the main method and a method to return a greeting
 * message.
 */
public class App {
    /**
     * Returns a greeting message.
     *
     * @return a greeting message
     */
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Hello TensorFlow " + TensorFlow.version());

        // Example usage of Gson
        Gson gs = new Gson();
        Todo todo = new Todo("Sample Task", "This is a sample task description", false, "2023-12-31", "High",
                "1", "2023-01-01T00:00:00Z", "2023-01-02T00:00:00Z");
        String json = gs.toJson(todo);
        System.out.println("Serialized Todo: " + json);
        System.out.println();
        Todo deserializedTodo = gs.fromJson(json, Todo.class);
        System.out.println(
                "Deserialized Todo: " + deserializedTodo.getTitle() + " - " + deserializedTodo.getDescription());

    }
}


/*
 * Hello World!
Serialized Todo: {"title":"Sample Task","description":"This is a sample task description","completed":false,"dueDate":"2023-12-31","priority":"High","id":"1","createdAt":"2023-01-01T00:00:00Z","updatedAt":"2023-01-02T00:00:00Z"}

Deserialized Todo: Sample Task - This is a sample task description
 */