/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    // https://mvnrepository.com/artifact/org.json/json
    implementation("org.json:json:20250517")

    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    implementation("com.google.code.gson:gson:2.13.1")

    // https://mvnrepository.com/artifact/org.tensorflow/tensorflow
    implementation("org.tensorflow:tensorflow:1.15.0")

    // https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-core
    // implementation("org.deeplearning4j:deeplearning4j-core:1.0.0-M2.1")
    // compile group: 'org.tensorflow', name: 'tensorflow-core-platform', version: '0.3.3'
    implementation("org.tensorflow:tensorflow:1.15.0")
    implementation("org.tensorflow:tensorflow-core-platform:0.3.3")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
